spring:
  application:
    name: apigateway

  cloud:
   gateway:
    mvc:
     routes:  
       - id: USERMICROSERVCIE
         uri: lb://USERMICROSERVCIE
         predicates: 
          - Path=/users/**
       - id: HOTELMICROSERVICE
         uri: lb://HOTELMICROSERVICE
         predicates: 
          - Path=/hotels/**,/staffs/**
       - id: RATINGSERVICE
         uri: lb://RATINGSERVICE
         predicates: 
          - Path=/ratings/**
  
  config:
    import:
    - configserver:http://localhost:8085      
          


server:
  port: 8084

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka 

# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true
#     config-url: /v3/api-docs/swagger-config
#     urls:
#       - url: /users/v3/api-docs
#         name: User Service
#       - url: /hotels/v3/api-docs
#         name: Hotel Service      
#       - url: /ratings/v3/api-docs
#         name: Rating Service      


         
    



