spring:
  application:
    name: apigateway

  cloud:
   gateway:
    mvc:
     routes:  
       - id: USERMICROSERVCIE
         uri: lb://USERMICROSERVCIE
         predicates: 
          - Path=/users/**
       - id: HOTELMICROSERVICE
         uri: lb://HOTELMICROSERVICE
         predicates: 
          - Path=/hotels/**,/staffs/**
       - id: RATINGSERVICE
         uri: lb://RATINGSERVICE
         predicates: 
          - Path=/ratings/**
          


server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 


         
    



